config/routes.rb
Rails.application.routes.draw do
  root    'static_pages#home'
  get 'signup' => 'users#new'
  resources :users

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :pet
  validates :user_id, presence: true
  validates :pet_id, presence: true
end

app/models/pet.rb
class Pet < ActiveRecord::Base
  has_many :favorites
  has_many :users, through: :favorites
  VALID_NAME_REGEX = /\A[a-zA-Z\-.\s]+\z/
  enum species: [:dog, :cat]
  enum sex: [:male, :female]
  enum size: [:small, :medium, :large]
  enum fixed: [:neutered, :spayed]
  validates :sex, presence: true, inclusion:     { in: sexes.keys }
  validates :size, presence: true, inclusion:    { in: sizes.keys }
  validates :species, presence: true, inclusion: { in: species.keys }
  validates :fixed, presence: true, inclusion:  { in: fixeds.keys }
  validates :breed, presence: true, format:     { with: VALID_NAME_REGEX }
  validates :name, presence: true, format:      { with: VALID_NAME_REGEX }
  validates :bio, presence: true, length:       { minimum: 13, maximum: 500 }
  validates :age, presence: true, numericality: { only_integer: true, greater_than: 0, less_than: 193 }
  validates :weight, presence: true, numericality: { only_integer: true, greater_than: 0, less_than: 130 }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :favorites
  has_many :pets, through: :favorites
  before_save { email.downcase! }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  has_secure_password

  def favorite(pet)
    favorites.create(pet_id: pet.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def index
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

    private

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'PawAdoptr', '/', class: 'navbar-brand' %>
    </div>
     <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Adopt</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">myPaw <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Log-in</a></li>
            <li><a href="#">Privacy</a></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Sign-up', signup_path %></li>
          </ul>
        </li>
      </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PawAdoptr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/navbar' %>
<%= render 'layouts/flash_messages' %>

<div class="container">
  <%= yield %>
</div>
<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
<div id="error_explanation">
  <div class="alert alert-danger">
    The form contains <%= pluralize(@user.errors.count, "error") %>.
  </div>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/static_pages/home.html.erb
<div class="div" id="main-banner">
    <img class="img-responsive center-block" src="/assets/test3.jpg" alt="Dogs and Cats">
</div>

app/views/users/new.html.erb
<h1>Sign-up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= @user.email %>